---

include:
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 5.0.1
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 2.1.1
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.4.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 3.11.0
    file: gitlab-ci.yml

variables:
  APP_NAME: ansible
  SEMANTIC_CONFIG_FILE: changelog
  DOCKER_PUBLIC_REGISTRY_URL: docker.io
  DOCKER_PUBLIC_REGISTRY_USERNAME: ${PUBLIC_REGISTRY_USERNAME}
  DOCKER_PUBLIC_REGISTRY_PASSWORD: ${PUBLIC_REGISTRY_PASSWORD}
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'

stages:
  - lint
  - build
  - test
  - publish
  - release

publish-feature:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg ANSIBLE_VERSION=${VERSION}
    TAG: "${CI_COMMIT_REF_SLUG}-${VERSION}"
  parallel:
    matrix:
      - NAME: [ 'VERSION' ]
        VERSION: [ '2.9', '2.10', '2.11' ]

delete-feature:docker:
  variables:
    TAG: '${CI_COMMIT_REF_SLUG}-2.9 ${CI_COMMIT_REF_SLUG}-2.10 ${CI_COMMIT_REF_SLUG}-2.11'

publish-release:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg ANSIBLE_VERSION=${VERSION}
    TAG: "${VERSION}"
  parallel:
    matrix:
      - NAME: [ 'VERSION' ]
        VERSION: [ '2.9', '2.10', '2.11' ]

publish-public-release:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg ANSIBLE_VERSION=${VERSION}
    TAG: "${VERSION}"
  parallel:
    matrix:
      - NAME: [ 'VERSION' ]
        VERSION: [ '2.9','2.10', '2.11' ]
...
